 ## examples/handle_exception.av

 try {
  throw "an exception";
 } catch(e) {
  pst(e);
 } finally {
  p("finally");
 }

 try {
  throw new IllegalArgumentException("test");
 } catch(IllegalArgumentException e) {
  p("catch IllegalArgumentException.");
  pst(e);
 } catch(e) {
  p("catch all throwable.");
  pst(e);
 }

